### ISSUE TITLE
DID Versions

### ISSUE THREAD

**Issue by domwoe** [hyperledger/indy-did-method#19]
The [spec](https://hyperledger.github.io/indy-did-method/#did-versions) says:

_If the parameter versionId is used, the value must be an Indy ledger seqno for the requested NYM on the queried Indy ledger. Instead of using the GET_NYM call, the Indy GET_TXN call is used, passing in the seqno. The result is checked that it is the NYM matching the DID namespace identifier. If so the call is considered to have failed. Either way, the process continues at Step 4._

Currently, NYM transactions in Indy are partial updates, i.e. a transaction with seqNo `i` might only set the verkey but not the didDocContent, but a prior transaction with seqNo `j` and `j<i` might have set the didDocContent. If we just use GET_TXN we would generate a base DID Doc, but don't include the prior didDocContent. 

I think we have the following options:

1. Don't allow specifying a versionId ([timestamp is simpler](https://github.com/hyperledger/indy-plenum/blob/master/docs/source/storage.md#6-timestamp-storage))
2. Don't allow partial updates (not backwards compatible)
3. Introduce GET_NYM with version/seqNo 
a. Store mapping `seqNo -> state` in indy node 
b. Get txn internally, get timestamp from txn and use `timestamp -> state` mapping 
4. Implement only in resolver/client. Use GET_TXN to get timestamp of transaction and then use GET_NYM with timestamp

**Comment by swcurran** [comment]
I assume there is nothing in the indy-node data indexing that allows us to find `j` when accessing `i`, such that accessing `i` always returns all of the data as of that transaction?   Without that, this is really painful.  To me, that would be the preferred option -- that there be an efficient way to find the history of a NYM to allow assembly of all of the data from a given point. Perhaps that should be another option?  On the other hand, is indexing necessary to be able to support versionID and versionTime?

> Hmmm....re-reading what I wrote ^^^ -- I think I'm just talking about your option 3. :-)

Failing that, I think my recommendation would be to use 2, but I'm not sure we can do that (or at least not without changes).  As I recall, if you specify "verkey", and you are not the DID Owner (e.g. per the config rules), you can't update the DID, even if you are not changing the "verkey".  

> Example -- as a Trustee, I created a DID as an Endorser, and was then asked to "demote" the DID to an author.  I tried to do that by specifying the new role and leaving the rest of the transaction the same (e.g. including the verkey) and that wouldn't work. However, all I needed to do was leave off the verkey and all good. 

We _could_ get around that by adding a "has it changed" check to the validation and allowing a transaction to proceed if a value has not changed as if it wasn't there, but that seems risky.

**Comment by domwoe** [comment]
Yep, option(s) seem to be most reasonable.
3a and 3b are different options. 3a is more complex to implement. 3b leads to a costlier read request. 

We have an initial implementation of 3b here: https://github.com/boschresearch/indy-node/blob/feature/did-indy/indy_node/server/request_handlers/read_req_handlers/get_nym_handler.py

**Comment by swcurran** [comment]
Resolved with the latest updates to the spec and implementation.
