### ISSUE TITLE
Use a hash to form namespace identifier

### ISSUE THREAD

**Issue by ekr** [hyperledger/indy-did-method#26]
The current specification only describes how to form a did:indy
for Ed25519 keys:

    For an Ed25519 key: Convert into Base58char the first 16 bytes of
    the 256 bit public key (verkey).

This seems ill-advised for two reasons:

1. You will need new specification text for any new algorithm.
2. It is not necessarily secure for future algorithms. Indeed, 
   I don't know that it's secure for Ed25519, though
   I don't know of an attack better than 2^128.

A better design would be to specify that the namespace identifier
is the first 16 bits of a SHA-256 hash of the public key. This
should be equally applicable for any algorithm.

**Comment by swcurran** [comment]
Given that the approach listed has been the convention, we'll need to have a backwards compatible path.  I'll do a PR to propose this, as I think you are right -- this is a more appropriate way to do it.

**Comment by swcurran** [comment]
PR has resolved this issue.
