### ISSUE TITLE
DID Namespace Syntax - restrict to lower case letters ?

### ISSUE THREAD

**Issue by c2bo** [hyperledger/indy-did-method#30]
The current did:indy spec defines the DID Namespace Identifier as
```
namespace     = namestring (":" namestring) ":"
namestring    = ALPHA *(ALPHA / DIGIT / "_" / "-")
```

While this is allowed according to the w3c did-core specification, imho it would make sense to also restrict the did:indy specific namespace to lowercase characters similar to the prefix (did:indy) to avoid misconfiguration/confusion:

```
namestring    = lowercase *(lowercase / DIGIT / "_" / "-")
lowercase     = %x61-7A ; a-z
```

**Comment by paulbastian** [comment]
approve

**Comment by swcurran** [comment]
Once we deal with the ":" vs. "." issue, we'll add a PR for this to prevent a merge conflict.

I also agree with this one.

**Comment by c2bo** [comment]
Good point, I just wanted to create a PR but forgot about that : to . change for the namespace part. I will check before next indy contributors call and create a PR for this change if the other change is merged.

**Comment by swcurran** [comment]
Fixed.
