### ISSUE TITLE
diddocContent relative IDs

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/indy-did-method#33]
When writing a nym with `diddocContent`, we should omit the `did:indy:<network>:<method-specific-id>` portion from the IDs of verification methods and services. This accomplishes a few things:

- Trivially write the same `diddocContent` to multiple ledgers
- The ledger itself does not have any awareness of `did:indy` (simplifies implementation)
- The ledger is not aware which network it is (sovrin vs idunion, etc) based on what is written to the ledger
- Shorten `diddocContent`

It is important to note that this would render the services and verification methods listed in `diddocContent` divergent from the DID Core specification and on resolution, the resolver would need to make these IDs absolute to produce a valid DID Document. This contrasts with the verification relationship sections of DID Documents (such as `authentication` or `authorization`) where relative DID URLs are acceptable according to the DID Core spec.

To demonstrate what is intended, consider the following `diddocContent` taken from the current version of the Indy method spec:

```json
"diddocContent" : {
    "@context" : [ 
        "https://www.w3.org/ns/did/v1",
        "https://identity.foundation/didcomm-messaging/service-endpoint/v1"
    ],
    "serviceEndpoint": [
        {
          "id": "did:indy:sovrin:123456#didcomm",
          "type": "didcomm-messaging",
          "serviceEndpoint": "https://example.com",
          "recipientKeys": [ "#verkey" ],
          "routingKeys": [ ]
        }
    ]
  }
```
This would instead look like:
```json
"diddocContent" : {
    "@context" : [ 
        "https://www.w3.org/ns/did/v1",
        "https://identity.foundation/didcomm-messaging/service-endpoint/v1"
    ],
    "serviceEndpoint": [
        {
          "id": "#didcomm",
          "type": "didcomm-messaging",
          "serviceEndpoint": "https://example.com",
          "recipientKeys": [ "#verkey" ],
          "routingKeys": [ ]
        }
    ]
  }
```

This would also mean that all verification method references to the current document must be made relative as well:
```json
"diddocContent" : {
    "@context" : [ 
        "https://www.w3.org/ns/did/v1",
        "https://identity.foundation/didcomm-messaging/service-endpoint/v1"
    ],
    "serviceEndpoint": [
        {
          "id": "#didcomm",
          "type": "didcomm-messaging",
          "serviceEndpoint": "https://example.com",
          "recipientKeys": [ "#verkey" ],
          "routingKeys": [ ]
        }
    ],
    "authentication": ["did:indy:sovrin:123456#verkey"]
  }
```
Becomes:
```json
"diddocContent" : {
    "@context" : [ 
        "https://www.w3.org/ns/did/v1",
        "https://identity.foundation/didcomm-messaging/service-endpoint/v1"
    ],
    "serviceEndpoint": [
        {
          "id": "#didcomm",
          "type": "didcomm-messaging",
          "serviceEndpoint": "https://example.com",
          "recipientKeys": [ "#verkey" ],
          "routingKeys": [ ]
        }
    ],
    "authentication": ["#verkey"]
  }
```

**Comment by dbluhm** [comment]
Relative IDs in `verificationMethod` and `service` can be enforced by the ledger. Verifying relative URLs in verification relationships would require the ledger to know it's network name (which is something I'd like to avoid if possible) and would therefore be trickier to validate and enforce on the ledger.

**Comment by swcurran** [comment]
Discussed on the call and we've agreed that this need not be done.
