### ISSUE TITLE
Versioning of the did method

### ISSUE THREAD

**Issue by paulbastian** [hyperledger/indy-did-method#37]
I haven't found a versioning in the document yet and I think it makes sense to include that at some point.

**Comment by swcurran** [comment]
@swcurran to investigate -- version and release number.

**Comment by swcurran** [comment]
Added PR #54 to address this.

**Comment by domwoe** [comment]
Closed with merge of PR #54 in [Indy DID Method Specification Call](https://wiki.hyperledger.org/display/indy/2022-03-01%3A+Indy+DID+Method+Specification+Call)
