### ISSUE TITLE
Missing Timestamp definition

### ISSUE THREAD

**Issue by MichScha** [hyperledger/indy-did-method#39]
In the indy-node transaction specification we have a definition for timestamp. As expected we use "integer as POSIX timestamp". I think we should also specify that in the did:indy spec for implementation clarification.

**Comment by domwoe** [comment]
Good point!
There's actually a requirement by [DID core to use a XML datetime for versionTime](https://www.w3.org/TR/did-core/#did-parameters) which we need to comply with.

On the implementation side the question is now if Indy VDR translates between unix timestamp and XML datetime or if Indy node accepts XML datetime.

**Comment by domwoe** [comment]
This is also a bit strange in the [Revocation Registry Entry](https://hyperledger.github.io/indy-did-method/#revocation-registry-entry) definition.

Here `?versionId=<timestamp>` is used. We could do this with a UNIX timestamp and be DID core compliant. However, it would be more coherent if we would use `?versionTime=<XML datetime>`.

**Comment by MichScha** [comment]
- "valid XML datetime value" from [did-core](https://www.w3.org/TR/did-core/#did-parameters) - Example: 2020-12-20T19:17:47Z
- "integer as POSIX timestamp" from [indy-node](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/requests.html#get-revoc-reg) - Example:1644326808

I have searched through the github issue of did-core but haven´t found the decision record why _XML datetime_ is been used. If we target did-core compliance we should go with XML datetime.

**Comment by paulbastian** [comment]
The did:indy [REVOG_REG_ENTRY](https://hyperledger.github.io/indy-did-method/#revocation-registry-entry) currently mixes together two underlying indy-node mechanisms:
- [GET_REVOC_REG Txn](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/requests.html#get-revoc-reg) to get the accumulator value for a certain point of time - here the W3C `?versionTime=<XML datetime> ` would fit
- [GET_REVOC_REG_DELTA Txn](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/requests.html#get-revoc-reg-delta) - here the W3C spec would not fit

Maybe it makes sense for the latter to separate that into a different did:indy path to avoid confusion?

**Comment by MichScha** [comment]
Do we want to have two different meanings for **timestamp**? I think least in the implementation we should expect one specific type?

We have currently also a different interpretation of versionId itself.

- `[?versionId=<timestamp>]` @GET_REVOC_REG Txn<=> [If the parameter is left off the current time is used for the **timestamp**](https://hyperledger.github.io/indy-did-method/#revocation-registry-entry)
- `versionId` @did Versions<=> [If the parameter versionId is used, the value must be an **Indy ledger seqno** for the requested [NYM] on the queried Indy ledger](https://hyperledger.github.io/indy-did-method/#did-versions)

**Comment by domwoe** [comment]
@swcurran I could take care of this if you want

**Comment by domwoe** [comment]
I'll take care of this issue together with #52  when there's a decision on #52.
