### ISSUE TITLE
DID URL for ATTRIB

### ISSUE THREAD

**Issue by domwoe** [hyperledger/indy-did-method#40]
I think the section for the [DID URL of an ATTRIB](https://hyperledger.github.io/indy-did-method/#attrib) is not very clear.

1. I would change the DID URL to `did:indy:sovrin:5nDyJVP1NrcPAttP3xwMB9/ATTRIB/endpoint` in accordance to the other ledger objects.
2. I don't understand the `existing identifier` and I think there is not really an existing identifier

I can do a PR that addresses this.

**Comment by paulbastian** [comment]
Whats the role of ATTRIB in general in the did:indy future? Isn't its main functionality to be replaced by the `didDocContent` in NYM?

**Comment by swcurran** [comment]
Most covered by #44 . Another PR to be added for the indy-did DID resolver API.
