### ISSUE TITLE
Do we allow authentication and verificationMethod as strings in DidDocContent?

### ISSUE THREAD

**Issue by domwoe** [hyperledger/indy-did-method#47]
The [current spec](https://hyperledger.github.io/indy-did-method/#diddoc-assembly-steps) is not entirely clear if `authentication` and `verificationMethod` items in `diddocContent` MUST be arrays or if strings are allowed. 

The DID core spec says that both MUST be arrays. I think we should either

1. Explicitly require arrays and validate/enforce this in indy node
2. Allow strings and add them to the respective arrays at resolution.

I'd prefer 1, but good with both.

**Comment by domwoe** [comment]
From the viewpoint of a resolver who needs to merge the data structures, I want to be certain what I get. 

I agree that the spec is clear about the base DIDDoc template.
But the description of the diddocContent is less clear:

```
If the diddocContent item contains verificationMethod and/or authentication items, process them as follows.
1. The entries MUST NOT have the same id values as those from the [NYM](https://hyperledger.github.io/indy-did-method/#term:nym)-generated DIDDoc. If a matching id is found, exit and return an error.
2. Merge the entries into the respective arrays of DIDDoc.
```

However, the important point for me is that indy-node will only accept arrays on write.

**Comment by swcurran** [comment]
@domwoe to add a PR. Code to check that if the `verificationMethod` and `authentication` are included, they must be arrays. This is in the indy-node code and any resolver.
