### ISSUE TITLE
Version of ATTRIB txn

### ISSUE THREAD

**Issue by domwoe** [hyperledger/indy-did-method#62]
The did:indy method allows to fetch the state of `NYM` data for different `versionId`s and `versionTime`s.

However , if the `NYM` data does not contain the `diddocContent` field, we fall back on trying to fetch the `ATTRIB` endpoint data. The `GET_ATTRIB` txn does not support these query parameters and we'll currently get a mix of `NYM` data for a specific version and the latest `ATTRIB` data.

**Comment by c2bo** [comment]
I guess we can close this issue, as it was implemented in indy-node [https://github.com/hyperledger/indy-node/commit/01add1fbff79a05c2f02ea0c6b30ee3fbb95d35e](https://github.com/hyperledger/indy-node/commit/01add1fbff79a05c2f02ea0c6b30ee3fbb95d35e) if I understand it correctly?
